# Generated by Django 2.2.5 on 2019-09-24 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sassyi_api', '0004_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='card',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sassyi_api.Card'),
        ),
    ]
